// Generated by Wrangler by running `wrangler types`

interface Env {
	DEFAULT_DOMAIN: "cfagentmail.com";
	ALLOW_AUTO_PROVISION_INBOX: "true";
	ATTACHMENTS: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
}
